Month8/step1
NataliyaNikulshina/react-burger pull request #4
Opened 2022-12-17 17:49 UTC by NataliyaNikulshina

2022-12-17 20:16 UTC, randomroot requested changes
**Доброго времени суток!** ☀️ 🌙 

Вы провели очень хорошую работу по добавлению контекста в ваш проект! Тем не менее, есть важный момент, который следует исправить для сдачи работы на данном этапе:

- При закрытии модального окна происходит отправка заказа (функция переключения видимости совпадает как для открытия, так и закрытия);

Также, в рамках ревью были предложены **улучшения** вашего кода, которое могут повысить его качество, исправить возможные проблемы в будущем и углубить ваше значение по курсу, внимательно ознакомьтесь с ними, т.к. часть из них могут стать критичными на следующих этапах.

**Успешного вам рефакторинга, хорошего настроения и отличного дня!** 🐈

2022-12-17 20:16 UTC, randomroot commented on src/utils/api.js
> +  urlBurger: "https://norma.nomoreparties.space/api/orders",
🟡 **Можно улучшить:**

Целесообразно вынести в отдельную константу базовый путь до API `https://norma.nomoreparties.space/api`, а отдельные пути уже суммировать с ним :)

2022-12-17 20:16 UTC, randomroot commented on src/utils/api.js
> +  }).then((res) => checkJson(res));
🟡 **Можно улучшить:**

Т.к. кол-во параметров у функции `checkJson` и результата в `then` совпадает, то можно передать функцию напрямую: `then(checkJson)`.

2022-12-17 20:16 UTC, randomroot commented on src/components/burger-ingredients/burger-ingredients.js
> +  console.log(data.data);
🟡 **Можно улучшить:**

Целесообразно убрать логгирование, используемое на этапе разработки и отладки, чтобы уменьшить кол-во информации, которое выводится в консоль :)

2022-12-17 20:16 UTC, randomroot commented on src/context/app-context.js
> +export const TotalPriceContext = createContext(null);
🟡 **Можно улучшить:**

Использование контекста для хранение цены несколько излишне, т.к. основная его цель - обеспечить удобную передачу данных между компонентами, чтобы избежать множественного проброса пропсов. В данном случае цену лучше хранить локально в конструкторе

2022-12-17 20:16 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.js
> +    return total;
🟡 **Можно улучшить:**

1) В данном случае использование функции `map` нецелесообразно, т.к. она создает на выходе массив. Для подсчёта стоимости заказа лучше подходит функция `reduce` (см. https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce)
2) Для мемоизации значения и уменьшения кол-ва рендеров рассмотрите возможность применения хука `useMemo` (см. https://ru.reactjs.org/docs/hooks-reference.html#usememo)

2022-12-17 20:16 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.js
> +  const [totalPrice, setTotalPrice] = React.useState(0);
🟡 **Можно улучшить:**

Т.к. `setTotalPrice` не используется, то использование стейта не целесообразно

2022-12-17 20:16 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.js
> +    const dataId = data.data.map((item) => item._id);
🟡 **Можно улучшить:**

Обратите внимание, что в заказе должно присутствовать два идентификатора булки - в начале массива и в конце. Это будет актуально на следующем этапе данного спринта.

2022-12-17 20:16 UTC, randomroot commented on src/components/total-price/total-price.js
> +  const { totalPrice } = useContext(TotalPriceContext);
🟡 **Можно улучшить:**

1) Обратите внимание, что `totalPrice` здесь - это одновременно и название переменной и имя из импорта выше, что может вызывать проблемы, следует выбрать уникальные имена;
2) Т.к. `totalPrice` не используется, то контекст не является актуальным, имеет смысл отказаться от его использования

2022-12-17 20:16 UTC, randomroot commented on src/context/app-context.js
> +export const NumberOrderContext = createContext();
🟡 **Можно улучшить:**

Контекст не используется, поэтому имеет смысл его удалить

2022-12-17 20:16 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.js
> +        <TotalPriceContext.Provider value={{ totalPrice, setTotalPrice }}>
🟡 **Можно улучшить:**

Контекст не используется, поэтому имеет смысл его удалить

2022-12-17 20:16 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.js
> +    postOrder();
🔴 **Нужно исправить:**

При закрытии модального окна происходит отправка заказа

2022-12-17 20:16 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.js
> +          //    console.log(total);
🟡 **Можно улучшить:**

Неиспользуемый код имеет смысл удалять из файлов, чтобы поддерживать чистоту кода. В случае необходимости его восстановления можно воспользоваться средствами Git-a.

2022-12-17 20:16 UTC, randomroot commented on src/components/ingredient/ingredient.js
> +function PriceIngredient( {price} ) {
🟡 **Можно улучшить:**

1) Не следует хранить несколько компонентов в одном файле, выделите каждый из них в отдельный файл и папку, чтобы улучшить читаемость и упростить дальнейшее тестирование вашего кода;
2) Компоненты, которые являются небольшими не всегда целесообразно выносить из основного, лучше оставлять такой код в рамках исходного компонента, чтобы упростить дерево Реакта и уменьшить кол-во проброса данных

2022-12-17 20:16 UTC, randomroot commented on src/components/ingredient/ingredient.js
> +        <Counter count={count} size="default" />
🟡 **Можно улучшить:**

Значение счётчика имеет смысл показывать только тогда, когда оно больше нуля, согласно дизайну

2022-12-17 20:32 UTC, NataliyaNikulshina commented on src/utils/api.js
> +  urlBurger: "https://norma.nomoreparties.space/api/orders",
Сделано

2022-12-17 20:33 UTC, NataliyaNikulshina commented on src/utils/api.js
> +  }).then((res) => checkJson(res));
Сделано, нужно изучить

2022-12-17 20:46 UTC, NataliyaNikulshina commented on src/components/burger-ingredients/burger-ingredients.js
> +  console.log(data.data);
Сделано

2022-12-17 20:58 UTC, NataliyaNikulshina commented on src/components/ingredient/ingredient.js
> +function PriceIngredient( {price} ) {
Сделано

2022-12-17 20:58 UTC, NataliyaNikulshina commented on src/components/burger-constructor/burger-constructor.js
> +    postOrder();
Сделано

2022-12-17 21:02 UTC, NataliyaNikulshina commented on src/components/ingredient/ingredient.js
> +        <Counter count={count} size="default" />
Сделано

2022-12-18 16:50 UTC, NataliyaNikulshina commented on src/context/app-context.js
> +export const NumberOrderContext = createContext();
Сделано

2022-12-18 16:50 UTC, NataliyaNikulshina commented on src/components/burger-constructor/burger-constructor.js
> +        <TotalPriceContext.Provider value={{ totalPrice, setTotalPrice }}>
Сделано

2022-12-18 16:50 UTC, NataliyaNikulshina commented on src/components/burger-constructor/burger-constructor.js
> +          //    console.log(total);
Сделано

2022-12-18 16:51 UTC, NataliyaNikulshina commented on src/components/total-price/total-price.js
> +  const { totalPrice } = useContext(TotalPriceContext);
Сделано

2022-12-18 16:51 UTC, NataliyaNikulshina commented on src/components/burger-constructor/burger-constructor.js
> +  const [totalPrice, setTotalPrice] = React.useState(0);
Сделано

2022-12-18 16:52 UTC, NataliyaNikulshina commented on src/context/app-context.js
> +export const TotalPriceContext = createContext(null);
Сделано

2022-12-18 17:16 UTC, NataliyaNikulshina commented on src/components/burger-constructor/burger-constructor.js
> +    return total;
Сделано

2022-12-18 19:30 UTC, randomroot approved these changes
🟢 **Работа принята:**

Все необходимые правки были внесены, код улучшен согласно рекомендациям, критических замечаний больше не имеется, **так держать**👍

Отличная работа, **желаю вам хорошего дня и успехов в дальнейшем обучении**! 🐈

2022-12-30 16:15 UTC, merged